### ISSUE TITLE
adapt example on PyPi.org

### ISSUE THREAD

**Issue by laiki** [strictdoc-project/reqif#148]
The example code on [Pypi.org](https://pypi.org/project/reqif/), handling regifz files isn't working on Python3.10 as the iterator on the dictionary used so far is returning a string.
Please adapt the line
`for reqif_bundle in reqifz_bundle.reqif_bundles:`

to be 
`for key in reqifz_bundle.reqif_bundles.keys():`

as well as 
`for attachment in reqifz_bundle.attachments:`
to be
`for key, attachment in reqifz_bundle.attachments.items():`

or similar

**Comment by stanislaw** [comment]
Thanks for reporting this. I have just pushed an update in the README file. When I release a new Pip in a few days, the PyPI example will also get updated.

I have started creating the basic examples of how the reqif library can be scripted with Python. Here are they: https://github.com/strictdoc-project/reqif/tree/main/tests/integration/examples.

Let me know which examples would you like to see and also, please open your other issues if you still have difficulties when working with the library.

**Comment by laiki** [comment]
Hi Stanislav,I noticed that you provided a bunch if tests wich heloed me in getting my work done. Thanks for your nice projectBest regardsWasilis-------- Ursprüngliche Nachricht --------Von: Stanislav Pankevich ***@***.***>Datum: Mo., 11. Sept. 2023, 22:55An: strictdoc-project/reqif ***@***.***>Cc: Wasilios Goutas ***@***.***>, Author ***@***.***>Betreff: Re: [strictdoc-project/reqif] adapt example on PyPi.org (Issue #148)
Thanks for reporting this. I have just pushed an update in the README file. When I release a new Pip in a few days, the PyPI example will also get updated.
I have started creating the basic examples of how the reqif library can be scripted with Python. Here are they: https://github.com/strictdoc-project/reqif/tree/main/tests/integration/examples.
Let me know which examples would you like to see and also, please open your other issues if you still have difficulties when working with the library.
