### ISSUE TITLE
"Multi_valued" for datatype definitions not exported

### ISSUE THREAD

**Issue by DavidKroeter84** [strictdoc-project/reqif#172]
I don't know if this expected/desired behavior, but no matter what I specify in the datatype definition (ReqIFDataTypeDefinitonEnumeration), the multi_valued metadata is never exported into the reqIF output.

Is that due to missing code in data_type_parser.py (line 270ff in the case of enumerations)?

**Comment by stanislaw** [comment]
Hi @DavidKroeter84 , thanks for reporting.

All sorts of things can be still missing. Would you mind sharing here a minimal ReqIF sample that features a good ReqIFDataTypeDefinitonEnumeration example that we could use as a test fixture to fix this?

**Comment by DavidKroeter84** [comment]
Hi @stanislaw !

I think the form the reqIF standard suggests would look the following:

```
...
<DATATYPE-DEFINITION-ENUMERATION DESC="Requirement category" IDENTIFIER="type-reqtype" LAST-CHANGE="2019-01-01T00:00:00.000+02:00" LONG-NAME="Requirement type">
	<SPECIFIED-VALUES>
		<ENUM-VALUE IDENTIFIER="value-reqtype-hardware" LAST-CHANGE="2019-01-01T00:00:00.000+02:00" LONG-NAME="hardware">
			<PROPERTIES>
				<EMBEDDED-VALUE KEY="0" OTHER-CONTENT="hardware"/>
			</PROPERTIES>
		</ENUM-VALUE>
		<ENUM-VALUE IDENTIFIER="value-reqtype-project" LAST-CHANGE="2019-01-01T00:00:00.000+02:00" LONG-NAME="project">
			<PROPERTIES>
				<EMBEDDED-VALUE KEY="1" OTHER-CONTENT="project"/>
			</PROPERTIES>
		</ENUM-VALUE>
		<ENUM-VALUE IDENTIFIER="value-reqtype-software" LAST-CHANGE="2019-01-01T00:00:00.000+02:00" LONG-NAME="software">
			<PROPERTIES>
				<EMBEDDED-VALUE KEY="2" OTHER-CONTENT="software"/>
			</PROPERTIES>
		</ENUM-VALUE>
	</SPECIFIED-VALUES>
</DATATYPE-DEFINITION-ENUMERATION>

...

<ATTRIBUTE-DEFINITION-ENUMERATION IDENTIFIER="attr-reqtype" IS-EDITABLE="true" LAST-CHANGE="2019-01-01T00:00:00.000+02:00" LONG-NAME="Requirement type" MULTI-VALUED="false">
  <TYPE>
	  <DATATYPE-DEFINITION-ENUMERATION-REF>type-reqtype</DATATYPE-DEFINITION-ENUMERATION-REF>
  </TYPE>
  <DEFAULT-VALUE>
	  <ATTRIBUTE-VALUE-ENUMERATION>
		  <VALUES>
			  <ENUM-VALUE-REF>value-reqtype-software</ENUM-VALUE-REF>
		  </VALUES>
		  <DEFINITION>
			  <ATTRIBUTE-DEFINITION-ENUMERATION-REF>attr-reqtype</ATTRIBUTE-DEFINITION-ENUMERATION-REF>
		  </DEFINITION>
	  </ATTRIBUTE-VALUE-ENUMERATION>
  </DEFAULT-VALUE>
</ATTRIBUTE-DEFINITION-ENUMERATION>
```

Note that the **MULTI-VALUED** tag is only part of the **ATTRIBUTE-DEFINITION-ENUMERATION**.

**Comment by stanislaw** [comment]
Please check this: https://github.com/strictdoc-project/reqif/pull/173. I believe that you found some dead code 👍 Thanks for reporting this.

> Note that the MULTI-VALUED tag is only part of the ATTRIBUTE-DEFINITION-ENUMERATION.

Indeed, it looks like it.

**Comment by stanislaw** [comment]
Please confirm that this change makes sense to you as well, and I will release a new Pip.

**Comment by DavidKroeter84** [comment]
Hi @stanislaw 
Hm, but what about line 105? Is the attribute really unused?
I thought that the multi-value property shall be there, but only for enumerations

(in <CORE-CONTENT> <REQ-IF-CONTENT> <SPEC-TYPES> <SPEC-OBJECT-TYPE> <SPEC-ATTRIBUTES> <ATTRIBUTE-DEFINITION-ENUMERATION>, see my code snippets above)

But I must admit I am not 100% firm with the reqIF specification.
